# $FreeBSD$

PORTNAME=	libretro-shaders-glsl
DISTVERSION=	g20180405
CATEGORIES=	games

MAINTAINER=	greg@unrelenting.technology
COMMENT=	Collection of GLSL shaders for libretro

LICENSE=	GPLv3

USE_GITHUB=	yes
GH_ACCOUNT=	libretro
GH_PROJECT=	glsl-shaders
GH_TAGNAME=	01ad3df

.include <bsd.port.mk>
