GH_TAGNAME=	e517ad3
PKGNAMESUFFIX=	-devel
CONFLICTS=	openmw
MASTERDIR=	${.CURDIR}/../openmw

.include	"${MASTERDIR}/Makefile"
PORTVERSION=	0.42.0
LIB_DEPENDS=	libavcodec.so:multimedia/ffmpeg \
		libBulletCollision.so:devel/bullet \
		libboost_thread.so:devel/boost-libs \
		libMyGUIEngine.so:x11-toolkits/mygui-devel \
		libosg.so:graphics/osg \
		libunshield.so:archivers/unshield
