# $FreeBSD$

PORTNAME=	echo
PORTVERSION=	0.1.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library for querying and setting console echo status

LICENSE=	BSD3CLAUSE

USE_CABAL=

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
