# $FreeBSD$

PKGNAMESUFFIX=	-qt5

COMMENT=	Collection of C++/Qt5 classes designed to use the APIs of The Echo Nest

PLIST=		${PKGDIR}/pkg-plist.qt5

MASTERDIR=	${.CURDIR}/../libechonest
.include "${MASTERDIR}/Makefile"
