# $FreeBSD$

PORTNAME=	libnumbertext
PORTVERSION=	1.0.3
CATEGORIES=	textproc
MASTER_SITES=	https://github.com/Numbertext/libnumbertext/releases/download/${PORTVERSION:R}/

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Number to number name and money text conversion libraries

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/COPYING

USES=	libtool tar:xz

HAS_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
