# $FreeBSD$

PORTNAME=	glslang-devel
DISTVERSION=	Overload400-PrecQual.2000-12-Apr-2017
CATEGORIES=	devel graphics

MAINTAINER=	greg@unrelenting.technology
COMMENT=	OpenGL and OpenGL ES shader front end and validator

LICENSE=	BSD3DLABS
LICENSE_NAME=	Modified BSD License (3Dlabs/LunarG)
LICENSE_FILE=	${FILESDIR}/LICENSE
LICENSE_PERMS=	dist-mirror dist-sell pkg-mirror pkg-sell auto-accept

USES=	cmake:outsource compiler:c++11-lang

USE_GITHUB=	yes
GH_ACCOUNT=	KhronosGroup
GH_PROJECT=	glslang
GH_TAGNAME=	d5aedc199

.include <bsd.port.mk>
