# $FreeBSD$

PORTNAME=	xdot
PORTVERSION=	0.9
CATEGORIES=	x11 python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dbaio@FreeBSD.org
COMMENT=	Interactive viewer for Graphviz dot files

LICENSE=	LGPL3+

NO_ARCH=	yes
USES=		python:3.4+
USE_PYTHON=	autoplist distutils
USE_GNOME=	gtk30 cairo pygobject3

.include <bsd.port.mk>
