# $FreeBSD$

PORTNAME=	binaryen
DISTVERSION=	1.38.6
CATEGORIES=	devel

MAINTAINER=	greg@unrelenting.technology
COMMENT=	Compiler infrastructure and toolchain library for WebAssembly

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake:outsource compiler:c++11-lang

USE_GITHUB=	yes
GH_ACCOUNT=	WebAssembly

.include <bsd.port.mk>
